# Default Pull Reviewer configuration
# You can see all the configuration options at httpss://github.com/reviewdog/reviewdog/blob/main/docs/configuration.md

version: 1.0.0

settings:
  enabled: true

rules:
  - name: "Reviewers changes"
    id: reviewers_changes
    description: "Changes to the repository reviewer settings."
    enabled: true
    when:
      paths: ["README.md", "src/domain/**/*.ts"]
    reviewers:
      users: [aleeiix]
      required: 1